language: python
python: 2.7
env:
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3
before_install:
  - sudo apt-get install -y libjpeg-dev libgif-dev libpng-dev libz-dev
  - mkdir -p buildout-cache/downloads
  - mkdir -p buildout-cache/eggs
install:
  - python bootstrap.py -c test-$PLONE_VERSION.cfg
  - bin/buildout -t 10 -Nc test-$PLONE_VERSION.cfg
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage run bin/test
  - pip install -q coveralls
  - coveralls
after_failure:
  - firefox -v
